services:
  atlas:
    container_name: atlas
    image: ${DOCKER_IMAGE_TAG}
    restart: always
    #env_file:
    #  - .env # 本地开发使用（不要提交到 Git）
    # 或者使用环境变量（生产推荐）：
    environment:
      - DATABASE_URL=postgresql://postgres:p0stgr3s@117.72.204.201:5432/atlas
      - MILVUS_HOST=117.72.204.201
      - MILVUS_PORT=19530
      - OPENAI_API_KEY=sk-ispsfhypumyaekrzbklivoyuhinbqmvlfhdnzyilxcojluez
      - OPENAI_BASE_URL=https://api.siliconflow.cn/v1
      - CHAT_MODEL=Qwen/Qwen2.5-32B-Instruct
      - EMBEDDING_MODEL=Qwen/Qwen3-Embedding-0.6B
      - JWT_SECRET_KEY=matrix-net-tech
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30
      - DEBUG=false
      - METADATA_DIR=metadata_store
    volumes:
      - ./metadata_store:/app/metadata_store
      - ./uploads:/app/uploads
    networks:
      - matrix-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.atlas.rule=Host(`atlas.matrix-net.tech`) && PathPrefix(`/atlas`)" # 替换为你的域名
      - "traefik.http.routers.atlas.entrypoints=websecure"
      - "traefik.http.routers.atlas.service=atlas"
      - "traefik.http.routers.atlas.tls.certresolver=dnspodresolver"
      - "traefik.http.services.atlas.loadbalancer.server.port=8000"
networks:
  matrix-network:
    external: true
